### ISSUE TITLE
formatting issue in TTP

### ISSUE THREAD

**Issue by petigura** [lukehandley/ttp#8]
@jluby127 checkout this error. does correct code live in dev branch.

```
Round 2 Model Solved.
Total Time to finish round 2 solver:  350.89
Round 2 complete.
done
Prepare schedule for the TTP.
Error: column names not correct.
Column names must be this format and this order: ['Starname', 'RA', 'Dec', 'Exposure Time', 'Exposures Per Visit', 'Visits In Night', 'Intra_Night_Cadence'].
Time in Night for Observations: 4.6 hours.
Traceback (most recent call last):
  File "/Users/petigura/miniforge3/envs/kpf-cc/lib/python3.10/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/Users/petigura/miniforge3/envs/kpf-cc/lib/python3.10/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/Users/petigura/miniforge3/envs/kpf-cc/lib/python3.10/bdb.py", line 598, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/petigura/code/optimalAllocation/generateScript.py", line 83, in <module>
    solution = model.TTPModel(startObs, endObs, targlist, tel, savepath)
  File "/Users/petigura/code/ttp/model.py", line 23, in __init__
    self.create_nodes()
  File "/Users/petigura/code/ttp/model.py", line 38, in create_nodes
    for s in self.stars:
TypeError: 'NoneType' object is not iterable
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/petigura/code/ttp/model.py(38)create_nodes()
-> for s in self.stars:
```

**Comment by lukehandley** [comment]
Looks like this is probably an issue from upstream, since the columns were prepared incorrectly before the ttp was called.

**Comment by jluby127** [comment]
fixed in addPriorityBranch which was merged to main
